### ISSUE TITLE
 Configuration property "drachtio" is not defined

### ISSUE THREAD

**Issue by imdrpn** [davehorton/drachtio-siprec-recording-server#25]
node app
WARNING: No configurations found in configuration directory:/opt/drachtio-siprec-recording-server/config
WARNING: To disable this warning set SUPPRESS_NO_CONFIG_WARNING in the environment.
/opt/drachtio-siprec-recording-server/node_modules/config/lib/config.js:202
    throw new Error('Configuration property "' + property + '" is not defined');
    ^

Error: Configuration property "drachtio" is not defined
    at Config.get (/opt/drachtio-siprec-recording-server/node_modules/config/lib/config.js:202:11)
    at Object.<anonymous> (/opt/drachtio-siprec-recording-server/app.js:17:22)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:623:3)

**Comment by davehorton** [comment]
Right, I provide example configs in the config/ directory - see [default.json.example-freeswitch](https://github.com/davehorton/drachtio-siprec-recording-server/blob/master/config/default.json.example-freeswitch) and [default.json.example-rtpengine](https://github.com/davehorton/drachtio-siprec-recording-server/blob/master/config/default.json.example-rtpengine).

You need to copy one of them to config/default.json, edit if appropriate, before running the app.

Did you do that?
